// swift-tools-version: 5.7

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "task5",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "task5",
            targets: ["AppModule"],
            bundleIdentifier: "task.task5",
            teamIdentifier: "8D4N5A4FG6",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .map),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/airbnb/lottie-ios", "4.2.0"..<"5.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "Lottie", package: "lottie-ios")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)